# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-24 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passenger_server', '0002_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
