# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-24 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passenger_server', '0003_organization_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='drivingFor_id',
            field=models.IntegerField(default=-1),
        ),
    ]
