# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-24 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passenger_server', '0004_user_drivingfor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='drivers',
            field=models.IntegerField(default=0),
        ),
    ]
