# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-25 00:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('passenger_server', '0005_organization_drivers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='queue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='passenger_server.Organization'),
        ),
    ]
