# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-25 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passenger_server', '0006_user_queue'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='driver_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(default='', max_length=255),
        ),
    ]
