# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-25 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passenger_server', '0007_auto_20180725_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='location',
        ),
        migrations.AddField(
            model_name='user',
            name='latitude',
            field=models.CharField(default=0, max_length=60),
        ),
        migrations.AddField(
            model_name='user',
            name='longitude',
            field=models.CharField(default=0, max_length=60),
        ),
    ]
