# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-25 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passenger_server', '0008_auto_20180725_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(default='', max_length=255),
        ),
    ]
