# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-26 00:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passenger_server', '0009_user_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_level',
            field=models.IntegerField(default=1),
        ),
    ]
