# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-27 18:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passenger_server', '0010_user_user_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='queue_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 27, 18, 37, 4, 786871), null=True),
        ),
    ]
